## PANDAS

In [ ]:
Esta libreria sirve para almacenar de manera tomatricial datos que van a ser de diferente tipo. 

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import openpyxl

## Introducción a las series de datos

una serie de datos es un tipo de objeto que nos proporciona pandas 

In [9]:
Estudiantes=pd.Series([16,12,17], index=['Pepito','Maria','Ana'])
Estudiantes

Pepito    16
Maria     12
Ana       17
dtype: int64

In [10]:
Estudiantes['Ana']

np.int64(17)

In [11]:
Estudiantes['Pepito']

np.int64(16)

In [12]:
Estudiantes[1]

C:\Users\Usuario\AppData\Local\Temp\ipykernel_11744\4221754821.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Estudiantes[1]


np.int64(12)

In [13]:
Estudiantes.index

Index(['Pepito', 'Maria', 'Ana'], dtype='object')

In [14]:
Estudiantes.values

array([16, 12, 17])

In [15]:
Estudiantes.shape

(3,)

## Introducción a los DataFrame

Son series unidas, que generan diccionarios 

Como buena practica los dataframe se imprimen con display(nomDataFrame)

In [16]:
Estudiantes=pd.DataFrame({'Estudiantes':[16,12,17], 'Escolaridad':['S','S','U']}, index=['Pepito','Maria','Ana'])
Estudiantes

Estudiantes Escolaridad
Pepito           16           S
Maria            12           S
Ana              17           U

In [17]:
Estudiantes=pd.DataFrame({'Estudiantes':[16,12,17], 'Escolaridad':['S','S','U']}, index=['Pepito','Maria','Ana'])
Estudiantes
print('Hola')   ## en este caso no se muestra el dataframe

Hola


In [18]:
Estudiantes=pd.DataFrame({'Estudiantes':[16,12,17], 'Escolaridad':['S','S','U']}, index=['Pepito','Maria','Ana'])
display(Estudiantes)  ## con el display si se muestra el dataframe
print('Hola')

Estudiantes Escolaridad
Pepito           16           S
Maria            12           S
Ana              17           U

Hola


## Funciones de DataFrame

In [19]:
Estudiantes.dtypes

Estudiantes     int64
Escolaridad    object
dtype: object

In [20]:
Estudiantes.index

Index(['Pepito', 'Maria', 'Ana'], dtype='object')

In [22]:
Estudiantes.axes

[Index(['Pepito', 'Maria', 'Ana'], dtype='object'),
 Index(['Estudiantes', 'Escolaridad'], dtype='object')]

In [23]:
Estudiantes.columns

Index(['Estudiantes', 'Escolaridad'], dtype='object')

In [24]:
Estudiantes.values

array([[16, 'S'],
       [12, 'S'],
       [17, 'U']], dtype=object)

# Creación de Series y DataFrames 

## Series

In [3]:
Estudiantes={'Felipe':14,'Diana':15}
pd.Series(Estudiantes,index=['Felipe','Diana','Alejo'])

Felipe    14.0
Diana     15.0
Alejo      NaN
dtype: float64

In [4]:
pd.Series(8,index=['a','b','c'])

a    8
b    8
c    8
dtype: int64

## DataFrames

Se pueden crear a partir de arrays


In [5]:
A=np.array([[1,2],[4,6]])
print(A)

[[1 2]
 [4 6]]


In [7]:
A=np.array([[1,2],[4,6]])
pd.DataFrame(A, index=['a','b'], columns=['col1','col2'])

col1  col2
a     1     2
b     4     6

# Impotando Datos de un Archivo 

Por ejemplo podemos importar archivos almacenados, de diferentes tipos como xlsx (excel y planos)

In [10]:
df1=pd.read_excel('ejemplo.xlsx')
df1
## Entre los parentesis va el nombre del archivo que se va a importar

Mes  Ingreso  Gasto
0    Enero      200     50
1  Febrero      300     40
2    Marzo      150     90

In [17]:
df2=pd.read_csv('ejemploII.csv', encoding='latin-1')
df2
## Entre los parentesis va el nombre del archivo que se va a importar

ID , Nombre completo,Fecha de nacimiento
0              C0001 , Leandra Anna Malo Alba,31024
1             C0002 , Severo Granados Iglesia,31636
2                   C0003 , Lucho Andreu Amat,32979
3    C0004 , Matías Mauricio Castillo Barrera,35401
4          C0005 , Mauricio Guijarro Castelló,30816
..                                              ...
196             C0197 , Sandalio Baeza Grande,34994
197        C0198 , Gregorio Guerrero Palomino,30728
198               C0199 , Socorro de Higueras,28005
199               C0200 , Otilia Viana Torres,36027
200                C0201 , Luís Guzman Alsina,26381

[201 rows x 1 columns]

In [18]:
df2=pd.read_csv('ejemploII.csv', encoding='latin-1')
df2.head()
## Muestra las primeras 5 filas 

ID , Nombre completo,Fecha de nacimiento
0            C0001 , Leandra Anna Malo Alba,31024
1           C0002 , Severo Granados Iglesia,31636
2                 C0003 , Lucho Andreu Amat,32979
3  C0004 , Matías Mauricio Castillo Barrera,35401
4        C0005 , Mauricio Guijarro Castelló,30816

In [19]:
df2=pd.read_csv('ejemploII.csv', encoding='latin-1')
df2.tail()
## Muestra las últimas 5 filas 

ID , Nombre completo,Fecha de nacimiento
196       C0197 , Sandalio Baeza Grande,34994
197  C0198 , Gregorio Guerrero Palomino,30728
198         C0199 , Socorro de Higueras,28005
199         C0200 , Otilia Viana Torres,36027
200          C0201 , Luís Guzman Alsina,26381

In [21]:
df2=pd.read_csv('ejemploII.csv', encoding='latin-1')
display(df2.tail())
df2.shape
## Muestra que son 201 filas y 1 columna

ID , Nombre completo,Fecha de nacimiento
196       C0197 , Sandalio Baeza Grande,34994
197  C0198 , Gregorio Guerrero Palomino,30728
198         C0199 , Socorro de Higueras,28005
199         C0200 , Otilia Viana Torres,36027
200          C0201 , Luís Guzman Alsina,26381

(201, 1)

In [41]:
df2=pd.read_csv('listaClientes.csv', encoding='latin-1')
df2.tail()
## Muestra las últimas 5 filas 

ID, Nombre completo, Fecha de nacimiento
196       C0197, Sandalio Baeza Grande, 34994
197  C0198, Gregorio Guerrero Palomino, 30728
198         C0199, Socorro de Higueras, 28005
199         C0200, Otilia Viana Torres, 36027
200          C0201, Luís Guzman Alsina, 26381

In [45]:
df2=pd.read_csv('listaClientes.csv', encoding='latin-1', sep=", ")
df2.tail()
## Muestra las últimas 5 filas 

C:\Users\Usuario\AppData\Local\Temp\ipykernel_9936\3370614157.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df2=pd.read_csv('listaClientes.csv', encoding='latin-1', sep=", ")


"ID             Nombre completo Fecha de nacimiento"
196  "C0197       Sandalio Baeza Grande               34994"
197  "C0198  Gregorio Guerrero Palomino               30728"
198  "C0199         Socorro de Higueras               28005"
199  "C0200         Otilia Viana Torres               36027"
200  "C0201          Luís Guzman Alsina               26381"

In [53]:
df2=pd.read_csv('listaClientes.csv', encoding='latin-1', sep=', ')
df2.tail()
## Muestra las últimas 5 filas 

C:\Users\Usuario\AppData\Local\Temp\ipykernel_9936\3429569494.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df2=pd.read_csv('listaClientes.csv', encoding='latin-1', sep=', ')


"ID             Nombre completo Fecha de nacimiento"
196  "C0197       Sandalio Baeza Grande               34994"
197  "C0198  Gregorio Guerrero Palomino               30728"
198  "C0199         Socorro de Higueras               28005"
199  "C0200         Otilia Viana Torres               36027"
200  "C0201          Luís Guzman Alsina               26381"

In [55]:
df2=pd.read_csv('listaClientes.csv', encoding='latin-1', sep=", ")
df2.tail()
df2.shape
## Muestra las últimas 5 filas 

C:\Users\Usuario\AppData\Local\Temp\ipykernel_9936\2831050729.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df2=pd.read_csv('listaClientes.csv', encoding='latin-1', sep=", ")


(201, 3)

## Inspeccionando un DataFrame


In [56]:
df2=pd.read_csv('ejemploII.csv', encoding='latin-1')
df2.head(3)
## Muestra las primeras 5 filas 

ID , Nombre completo,Fecha de nacimiento
0     C0001 , Leandra Anna Malo Alba,31024
1    C0002 , Severo Granados Iglesia,31636
2          C0003 , Lucho Andreu Amat,32979

In [57]:
df2=pd.read_csv('ejemploII.csv', encoding='latin-1')
df2.sample()
## Muestra las primeras 5 filas 

ID , Nombre completo,Fecha de nacimiento
110  C0111 , Samanta Casandra Borrell Maestre,25591

In [58]:
df2=pd.read_csv('ejemploII.csv', encoding='latin-1')
df2.sample(6)
## Muestra las primeras 5 filas 

ID , Nombre completo,Fecha de nacimiento
140      C0141 , Óscar Dominguez Mayol,27018
103        C0104 , Ruben Marquez Belda,29851
123               C0124 , Marcia Tomas,35017
191     C0192 , Trinidad Salas Gimenez,27517
195  C0196 , Emelina Melisa Palau Seco,35916
93       C0094 , Primitivo Jaén Garcés,34743

In [59]:
df2=pd.read_csv('ejemploII.csv', encoding='latin-1')
df2.describe()
## Muestra las primeras 5 filas 

ID , Nombre completo,Fecha de nacimiento
count                                       201
unique                                      201
top        C0001 , Leandra Anna Malo Alba,31024
freq                                          1

In [60]:
df2=pd.read_csv('ejemploII.csv', encoding='latin-1')
df2.info()
## Muestra la información del dataframe con el que estamos trabajando  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype 
---  ------                                    --------------  ----- 
 0   ID , Nombre completo,Fecha de nacimiento  201 non-null    object
dtypes: object(1)
memory usage: 1.7+ KB


## Accediendo a Datos

In [73]:
df3=pd.read_csv('ejemploII.csv', encoding='latin-1', sep="/")
##df3.set_index('ID ')
display(df3.head())## Muestra el ID como indices

ID                    Nombre completo  Fecha de nacimiento
0  C0001             Leandra Anna Malo Alba                31024
1  C0002            Severo Granados Iglesia                31636
2  C0003                  Lucho Andreu Amat                32979
3  C0004  Matías Mauricio Castillo Barrera                35401
4  C0005        Mauricio Guijarro Castelló                30816

In [75]:
df3=pd.read_csv('ejemploII.csv', encoding='latin-1', sep="/")
df3.set_index('ID', inplace=True)
display(df3.head())## Muestra el ID como indices y ojo con el INPLACE= TRUE

Nombre completo  Fecha de nacimiento
ID                                                           
C0001             Leandra Anna Malo Alba                31024
C0002            Severo Granados Iglesia                31636
C0003                  Lucho Andreu Amat                32979
C0004  Matías Mauricio Castillo Barrera                35401
C0005        Mauricio Guijarro Castelló                30816

In [78]:
df3['Nombre completo'].head(20)
##Nos sirve para delimitar un dato dentro del dataFrame


ID
C0001               Leandra Anna Malo Alba
C0002              Severo Granados Iglesia
C0003                    Lucho Andreu Amat
C0004    Matías Mauricio Castillo Barrera
C0005          Mauricio Guijarro Castelló
C0006          Isaura Leyre Avilés Pelayo
C0007                   Soraya Morera-Lago
C0008          Victoriano Tapia-Cabanillas
C0009                    Nidia Saez Campoy
C0010           Teófila Villanueva Molina
C0011                     Trini de Alberdi
C0012                           Dani Baena
C0013                  Angelina de Arregui
C0014                   Samuel de Carranza
C0015           Jacinta Montenegro Garcés
C0016               Lisandro Delgado Nadal
C0017                Samanta Manjón Godoy
C0018         Albano Teodosio Cañete Rosa
C0019                      Abel Villanueva
C0020             Bienvenida Pulido Cózar
Name: Nombre completo, dtype: object

In [80]:
df3['Fecha de nacimiento'].head(20)
##Nos sirve para delimitar un dato dentro del dataFrame


ID
C0001    31024
C0002    31636
C0003    32979
C0004    35401
C0005    30816
C0006    31885
C0007    33204
C0008    29651
C0009    29339
C0010    31781
C0011    33211
C0012    28418
C0013    36577
C0014    36296
C0015    34406
C0016    29329
C0017    29283
C0018    29680
C0019    32306
C0020    34355
Name: Fecha de nacimiento, dtype: int64

In [81]:
df3.loc['C0001']
## Es para traer una fila en particular

Nombre completo        Leandra Anna Malo Alba
Fecha de nacimiento                     31024
Name: C0001, dtype: object

In [82]:
df3.iloc[34]
## Es para traer una fila en particular por su número

Nombre completo        Natalio Pereira Barrio
Fecha de nacimiento                     25830
Name: C0035, dtype: object